# Generated by Django 2.2.7 on 2019-11-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_material', models.CharField(help_text='Ingrese nombre del material solicitado', max_length=50)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, help_text='Ingrese la fecha en que se realiza el pedido')),
                ('hora', models.DateTimeField(auto_now=True)),
                ('nombre_alumno', models.CharField(help_text='Ingrese nombre del alumno que realiza el pedido', max_length=50)),
                ('apellido_alumno', models.CharField(help_text='Ingrese el apellido del alumno', max_length=50)),
                ('material', models.CharField(help_text='Ingrese material solicitado', max_length=70)),
                ('cantidad_materiales', models.PositiveSmallIntegerField(help_text='Ingrese la cantidad de productos solicitados')),
                ('estado_producto_entregado', models.CharField(choices=[('Buenas condiciones', 'Buenas condiciones'), ('Malas condiciones', 'Malas condiciones')], default='Buenas condiciones', help_text='Ingrese el estado del producto entregado', max_length=50)),
                ('estado_producto_devuelto', models.CharField(blank=True, choices=[('Buenas condiciones', 'Buenas condiciones'), ('Malas condiciones', 'Malas condiciones')], default='Buenas condiciones', help_text='Ingrese el estado del producto una vez este fue devuelto', max_length=50, null=True)),
                ('devuelto', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-fecha'],
            },
        ),
    ]
