# Generated by Django 2.2.1 on 2019-10-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_material', models.CharField(max_length=50)),
                ('nro_inventario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre_alumno', models.CharField(max_length=50)),
                ('apellido_alumno', models.CharField(max_length=50)),
                ('estado_producto_entregado', models.CharField(max_length=50)),
                ('estado_producto_devuelto', models.CharField(max_length=50)),
                ('cantidad_materiales', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo_materiales.Material')),
            ],
        ),
    ]
