# Generated by Django 2.2.6 on 2019-10-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['nombre_material'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
    ]
