# Generated by Django 2.2.6 on 2019-10-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_materiales', '0002_auto_20191023_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['fecha'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
