# Generated by Django 2.2.1 on 2019-10-28 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_materiales', '0003_auto_20191023_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='nro_inventario',
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre_material',
            field=models.CharField(help_text='Ingrese nombre del material solicitado', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='apellido_alumno',
            field=models.CharField(help_text='Ingrese el apellido del alumno', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cantidad_materiales',
            field=models.IntegerField(help_text='Ingrese la cantidad de productos solicitados'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_producto_devuelto',
            field=models.CharField(choices=[('Buenas condiciones', 'Buenas condiciones'), ('Malas condiciones', 'Malas condiciones')], default='Buenas condiciones', help_text='Ingrese el estado del producto una vez este fue devuelto', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_producto_entregado',
            field=models.CharField(choices=[('Buenas condiciones', 'Buenas condiciones'), ('Malas condiciones', 'Malas condiciones')], default='Buenas condiciones', help_text='Ingrese el estado del producto entregado', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(help_text='Ingrese la fecha en que se realizao el pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='material',
            field=models.ForeignKey(help_text='Ingrese material solicitado', on_delete=django.db.models.deletion.CASCADE, to='prestamo_materiales.Material'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre_alumno',
            field=models.CharField(help_text='Ingrese nombre del alumno que realiza el pedido', max_length=50),
        ),
    ]
