# Generated by Django 2.2.6 on 2019-10-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_materiales', '0004_auto_20191028_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='material',
            field=models.CharField(help_text='Ingrese material solicitado', max_length=70),
        ),
    ]
