# Generated by Django 2.2.6 on 2019-10-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_materiales', '0005_auto_20191030_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['fecha'], 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
    ]
