# Generated by Django 2.2.1 on 2019-10-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_materiales', '0006_auto_20191030_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(auto_now_add=True, help_text='Ingrese la fecha en que se realiza el pedido'),
        ),
    ]
