# Generated by Django 2.2.1 on 2019-11-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_materiales', '0007_auto_20191031_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_producto_devuelto',
            field=models.CharField(blank=True, choices=[('Buenas condiciones', 'Buenas condiciones'), ('Malas condiciones', 'Malas condiciones')], default='Buenas condiciones', help_text='Ingrese el estado del producto una vez este fue devuelto', max_length=50, null=True),
        ),
    ]
