# Generated by Django 2.2.1 on 2019-11-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_materiales', '0008_auto_20191101_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='devuelto',
            field=models.BooleanField(default=False),
        ),
    ]
