# Generated by Django 2.2.1 on 2019-11-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_materiales', '0010_auto_20191101_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='hora',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
