# Generated by Django 2.2.1 on 2019-11-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_materiales', '0011_pedido_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
    ]
