# Generated by Django 2.2.7 on 2019-11-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_materiales', '0013_auto_20191105_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha'], 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cantidad_materiales',
            field=models.PositiveSmallIntegerField(help_text='Ingrese la cantidad de productos solicitados'),
        ),
    ]
