# Generated by Django 2.2.7 on 2019-11-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_materiales', '0014_auto_20191105_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad_materiales',
            field=models.IntegerField(help_text='Ingrese la cantidad de productos solicitados'),
        ),
    ]
